# Generated by Django 5.2.14 on 2026-05-28 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='Slug')),
                ('provincia', models.CharField(choices=[('neuquen', 'Neuquén'), ('rio_negro', 'Río Negro'), ('chubut', 'Chubut'), ('santa_cruz', 'Santa Cruz'), ('tierra_del_fuego', 'Tierra del Fuego'), ('la_pampa', 'La Pampa')], max_length=30, verbose_name='Provincia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('mejor_epoca', models.CharField(blank=True, max_length=120, verbose_name='Mejor época para visitar')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de lugar',
                'verbose_name_plural': 'Tipos de lugar',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.lugar', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='lugar',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lugares', to='blog.tipolugar', verbose_name='Tipo de lugar'),
        ),
    ]
